// Дефолтные тексты лендинга для мини-CMS (автосборка).
// key: страница.секция.поле | section — вкладка | type: text|textarea|html
// Значение сидируется один раз; правки админа не затираются.
export const CONTENT_DEFAULTS = [
  // ── Главная ──
  { key: 'home.hero.title', section: 'Главная', label: 'Заголовок героя', type: 'html', sort: 10, value: 'AURIX MOTORS — это не просто аренда.<br><span class="fs-title-gold">Это стиль жизни.</span>' },
  { key: 'home.hero.lead', section: 'Главная', label: 'Подзаголовок героя', type: 'textarea', sort: 20, value: 'Круглосуточная подача по Москве. AURIX MOTORS делает аренду премиум-авто простой и быстрой.' },
  { key: 'home.categories.title', section: 'Главная', label: 'Заголовок «Категории»', type: 'text', sort: 30, value: 'Категории автопарка' },
  { key: 'home.experience.title', section: 'Главная', label: 'Заголовок «Опыт»', type: 'html', sort: 40, value: 'Мы создаём опыт,<br>который запоминается' },
  { key: 'home.fleet.title', section: 'Главная', label: 'Заголовок «Автопарк»', type: 'text', sort: 50, value: 'Наш автопарк' },
  { key: 'home.partner.title', section: 'Главная', label: 'Заголовок «Сдать авто»', type: 'html', sort: 60, value: '<span class="pt-title-accent">Сдаёте</span> авто<br>в аренду?' },
  { key: 'home.delivery.title', section: 'Главная', label: 'Заголовок «Доставка»', type: 'html', sort: 70, value: 'Доставка и получение<br>автомобиля' },
  { key: 'home.why.title', section: 'Главная', label: 'Заголовок «Почему мы»', type: 'text', sort: 80, value: 'Почему выбирают нас?' },
  { key: 'home.faq.title', section: 'Главная', label: 'Заголовок «FAQ»', type: 'html', sort: 90, value: 'Часто задаваемые<br>вопросы' },
  { key: 'home.search.city', section: 'Главная', label: 'Поиск — город', type: 'text', sort: 200, value: 'Москва' },
  { key: 'home.search.brandLabel', section: 'Главная', label: 'Поиск — подпись «Марка»', type: 'text', sort: 210, value: 'Марка' },
  { key: 'home.search.cta', section: 'Главная', label: 'Поиск — кнопка', type: 'text', sort: 220, value: 'Показать авто' },
  { key: 'home.perks.item0title', section: 'Главная', label: 'Преимущество 1 — заголовок', type: 'text', sort: 230, value: 'Полная страховка' },
  { key: 'home.perks.item0desc', section: 'Главная', label: 'Преимущество 1 — описание', type: 'text', sort: 240, value: 'Каско и ОСАГО включены в стоимость' },
  { key: 'home.perks.item1title', section: 'Главная', label: 'Преимущество 2 — заголовок', type: 'text', sort: 250, value: 'Подача 24/7' },
  { key: 'home.perks.item1desc', section: 'Главная', label: 'Преимущество 2 — описание', type: 'text', sort: 260, value: 'Доставим авто в удобное для вас время' },
  { key: 'home.perks.item2title', section: 'Главная', label: 'Преимущество 3 — заголовок', type: 'text', sort: 270, value: 'Без оклейки' },
  { key: 'home.perks.item2desc', section: 'Главная', label: 'Преимущество 3 — описание', type: 'text', sort: 280, value: 'Все авто без брендирования и наклеек' },
  { key: 'home.perks.item3title', section: 'Главная', label: 'Преимущество 4 — заголовок', type: 'text', sort: 290, value: 'Консьерж-сервис' },
  { key: 'home.perks.item3desc', section: 'Главная', label: 'Преимущество 4 — описание', type: 'text', sort: 300, value: 'Персональный менеджер на весь период аренды' },
  { key: 'home.perks.item4title', section: 'Главная', label: 'Преимущество 5 — заголовок', type: 'text', sort: 310, value: 'Аэропорты и отели' },
  { key: 'home.perks.item4desc', section: 'Главная', label: 'Преимущество 5 — описание', type: 'text', sort: 320, value: 'Подача в любую точку Москвы и МО' },
  { key: 'home.perks.item5title', section: 'Главная', label: 'Преимущество 6 — заголовок', type: 'text', sort: 330, value: 'Клуб привилегий' },
  { key: 'home.perks.item5desc', section: 'Главная', label: 'Преимущество 6 — описание', type: 'text', sort: 340, value: 'Доступ к закрытым мероприятиям и бонусам' },
  { key: 'home.categories.allLink', section: 'Главная', label: 'Категории — ссылка «весь автопарк»', type: 'text', sort: 350, value: 'Смотреть весь автопарк →' },
  { key: 'home.categories.item0', section: 'Главная', label: 'Категория 1', type: 'text', sort: 360, value: 'Внедорожники' },
  { key: 'home.categories.item1', section: 'Главная', label: 'Категория 2', type: 'text', sort: 370, value: 'Купе' },
  { key: 'home.categories.item2', section: 'Главная', label: 'Категория 3', type: 'text', sort: 380, value: 'Кабриолеты' },
  { key: 'home.categories.item3', section: 'Главная', label: 'Категория 4', type: 'text', sort: 390, value: 'Купе/Кабриолеты' },
  { key: 'home.categories.item4', section: 'Главная', label: 'Категория 5', type: 'text', sort: 400, value: 'Седаны' },
  { key: 'home.experience.lead', section: 'Главная', label: 'Мы создаём опыт — абзац', type: 'textarea', sort: 410, value: 'AURIX MOTORS — это не просто аренда авто. Это стиль жизни, свобода и эмоции за рулём лучших автомобилей мира.' },
  { key: 'home.fleet.allLink', section: 'Главная', label: 'Автопарк — ссылка «Смотреть все»', type: 'text', sort: 420, value: 'Смотреть все' },
  { key: 'home.fleet.moreBtn', section: 'Главная', label: 'Автопарк — кнопка «Ещё авто»', type: 'text', sort: 430, value: 'Ещё авто' },
  { key: 'home.reviews.headBefore', section: 'Главная', label: 'Отзывы — «Что говорят»', type: 'text', sort: 440, value: 'Что говорят' },
  { key: 'home.reviews.headAfter', section: 'Главная', label: 'Отзывы — «о нас»', type: 'text', sort: 450, value: 'о нас' },
  { key: 'home.reviews.headMuted', section: 'Главная', label: 'Отзывы — «тысячи клиентов»', type: 'text', sort: 460, value: 'тысячи клиентов' },
  { key: 'home.subscribe.mark', section: 'Главная', label: 'Баннер подписки — метка', type: 'text', sort: 470, value: 'АРЕНДА' },
  { key: 'home.subscribe.title', section: 'Главная', label: 'Баннер подписки — заголовок', type: 'text', sort: 480, value: 'Хотите арендовать дольше?' },
  { key: 'home.subscribe.subtitle', section: 'Главная', label: 'Баннер подписки — подзаголовок', type: 'text', sort: 490, value: 'Оформите подписку AURIX+ на длительный период.' },
  { key: 'home.subscribe.cta', section: 'Главная', label: 'Баннер подписки — кнопка', type: 'text', sort: 500, value: 'Подобрать подписку' },
  { key: 'home.partner.captionAcc', section: 'Главная', label: 'Сдаёте авто — подпись фото (акцент)', type: 'text', sort: 510, value: 'Удобное решение для вашего комфорта' },
  { key: 'home.partner.captionMain', section: 'Главная', label: 'Сдаёте авто — подпись фото', type: 'text', sort: 520, value: 'Зарабатывайте больше. Без усилий.' },
  { key: 'home.partner.desc', section: 'Главная', label: 'Сдаёте авто — описание', type: 'textarea', sort: 530, value: 'Покажите свой автопарк премиум-клиентам. Получайте брони. Полный контроль.' },
  { key: 'home.partner.cta', section: 'Главная', label: 'Сдаёте авто — кнопка', type: 'text', sort: 540, value: 'Разместить авто' },
  { key: 'home.delivery.lead', section: 'Главная', label: 'Доставка — абзац', type: 'textarea', sort: 550, value: 'AURIX MOTORS предлагает гибкие варианты получения и доставки авто, чтобы подстроиться под ваш график. Заберите авто в офисе или закажите доставку — быстро, удобно, по всей Москве.' },
  { key: 'home.delivery.card1title', section: 'Главная', label: 'Доставка — карточка 1 заголовок', type: 'text', sort: 560, value: 'Получение в офисе' },
  { key: 'home.delivery.card1text', section: 'Главная', label: 'Доставка — карточка 1 текст', type: 'textarea', sort: 570, value: 'Приезжайте в наш офис и заберите авто сами. Команда подготовит машину к вашему приезду — никаких ожиданий.' },
  { key: 'home.delivery.card2title', section: 'Главная', label: 'Доставка — карточка 2 заголовок', type: 'text', sort: 580, value: 'Доставка' },
  { key: 'home.delivery.card2li1', section: 'Главная', label: 'Доставка — пункт 1', type: 'html', sort: 590, value: '<strong>Бесплатная доставка по Москве.</strong> Доставим выбранный авто в любую точку города — отель, дом, офис — 24/7, без доплат.' },
  { key: 'home.delivery.card2li2', section: 'Главная', label: 'Доставка — пункт 2', type: 'html', sort: 600, value: '<strong>Доставка по области.</strong> Подача в Подмосковье и соседние регионы. Стоимость зависит от расстояния, но скорость и качество — на уровне.' },
  { key: 'home.delivery.pinTitle', section: 'Главная', label: 'Доставка — офис заголовок', type: 'text', sort: 610, value: 'Наш офис' },
  { key: 'home.delivery.pinAddr', section: 'Главная', label: 'Доставка — адрес офиса', type: 'text', sort: 620, value: 'Москва, Олимпийский проспект, 12' },
  { key: 'home.delivery.pinHours', section: 'Главная', label: 'Доставка — часы работы', type: 'text', sort: 630, value: 'Ежедневно, 10:00–20:00' },
  { key: 'home.why.card1title', section: 'Главная', label: 'Почему выбирают — карточка 1 заголовок', type: 'text', sort: 640, value: 'Полная страховка' },
  { key: 'home.why.card1text', section: 'Главная', label: 'Почему выбирают — карточка 1 текст', type: 'html', sort: 650, value: 'В стоимость включены КАСКО и ОСАГО. При ДТП не по вашей вине — <strong>ответственность 0 ₽</strong>. Никаких скрытых доплат.' },
  { key: 'home.why.card2title', section: 'Главная', label: 'Почему выбирают — карточка 2 заголовок', type: 'text', sort: 660, value: 'Доставка 24/7' },
  { key: 'home.why.card2text', section: 'Главная', label: 'Почему выбирают — карточка 2 текст', type: 'textarea', sort: 670, value: 'Нужен авто в аэропорт в 2 ночи или в отель в полдень? Доставим в любое время, в любую точку Москвы.' },
  { key: 'home.why.card3title', section: 'Главная', label: 'Почему выбирают — карточка 3 заголовок', type: 'html', sort: 680, value: 'Новые автомобили<br/>со всеми опциями' },
  { key: 'home.why.card3text', section: 'Главная', label: 'Почему выбирают — карточка 3 текст', type: 'textarea', sort: 690, value: 'Весь автопарк — новые модели с минимальным пробегом и полной комплектацией. Комфорт, стиль и динамика в каждой поездке.' },
  { key: 'home.why.card4title', section: 'Главная', label: 'Почему выбирают — карточка 4 заголовок', type: 'html', sort: 700, value: 'Прозрачные цены<br/>и полная страховка' },
  { key: 'home.why.card4text', section: 'Главная', label: 'Почему выбирают — карточка 4 текст', type: 'textarea', sort: 710, value: 'Никаких скрытых платежей. Чёткая цена и страхование в каждой аренде — сосредоточьтесь на дороге, а не на деталях.' },
  { key: 'home.faq.lead', section: 'Главная', label: 'FAQ — вводный абзац', type: 'textarea', sort: 720, value: 'Собрали ответы на самые популярные вопросы об аренде премиум-авто в AURIX MOTORS, чтобы вы могли спокойно планировать поездку без сомнений.' },
  // ── Тарифы ──
  { key: 'tariffs.head.title', section: 'Тарифы', label: 'Заголовок страницы', type: 'html', sort: 10, value: 'Тарифы <em>и цены</em>' },
  { key: 'tariffs.head.lead', section: 'Тарифы', label: 'Подзаголовок', type: 'textarea', sort: 20, value: 'Прозрачное ценообразование без скрытых платежей. Стоимость зависит от модели и срока аренды. Цена включает НДС 22%.' },
  { key: 'tariffs.table.note', section: 'Тарифы', label: 'Примечание под таблицей', type: 'textarea', sort: 30, value: 'Цена включает НДС 22%. Залог обязателен по всем автомобилям и возвращается после сдачи авто.' },
  { key: 'tariffs.notes.photo.title', section: 'Тарифы', label: 'Блок «Фотосессии» — заголовок', type: 'text', sort: 40, value: 'Аренда для фотосессий' },
  { key: 'tariffs.notes.photo.text', section: 'Тарифы', label: 'Блок «Фотосессии» — текст', type: 'textarea', sort: 50, value: 'Автомобиль можно арендовать для фотосессии или съёмки без пробега. Тариф указан за час. Возможна подача в любое место Москвы и МО.' },
  { key: 'tariffs.notes.gift.title', section: 'Тарифы', label: 'Блок «Сертификаты» — заголовок', type: 'text', sort: 60, value: 'Подарочные сертификаты' },
  { key: 'tariffs.notes.gift.text', section: 'Тарифы', label: 'Блок «Сертификаты» — текст', type: 'textarea', sort: 70, value: 'Подарочный сертификат на аренду любого автомобиля из парка. Стоимость сертификата равна стоимости одних суток аренды выбранного автомобиля. Срок действия — 1 год с даты оформления.' },
  { key: 'tariffs.notes.delivery.title', section: 'Тарифы', label: 'Блок «Доставка» — заголовок', type: 'text', sort: 80, value: 'Доставка и получение' },
  { key: 'tariffs.notes.delivery.text', section: 'Тарифы', label: 'Блок «Доставка» — текст', type: 'textarea', sort: 90, value: 'Доставка и забор автомобиля осуществляются за дополнительную плату в любое удобное место. Работаем ежедневно с 10:00 до 20:00, по предварительной договорённости — в нерабочее время. Свяжитесь с нами для уточнения стоимости.' },
  { key: 'tariffs.cta.button', section: 'Тарифы', label: 'Кнопка CTA', type: 'text', sort: 100, value: 'Выбрать автомобиль' },
  { key: 'tariffs.head.crumbHome', section: 'Тарифы', label: 'Хлебные крошки — Главная', type: 'text', sort: 200, value: 'Главная' },
  { key: 'tariffs.head.crumbCurrent', section: 'Тарифы', label: 'Хлебные крошки — текущая', type: 'text', sort: 201, value: 'Тарифы' },
  { key: 'tariffs.state.loading', section: 'Тарифы', label: 'Загрузка тарифов', type: 'text', sort: 203, value: 'Загрузка тарифов...' },
  { key: 'tariffs.table.colCar', section: 'Тарифы', label: 'Колонка — Автомобиль', type: 'text', sort: 204, value: 'Автомобиль' },
  { key: 'tariffs.table.col1_5', section: 'Тарифы', label: 'Колонка — 1–5 дней', type: 'text', sort: 205, value: '1–5 дней' },
  { key: 'tariffs.table.col6_12', section: 'Тарифы', label: 'Колонка — 6–12 дней', type: 'text', sort: 206, value: '6–12 дней' },
  { key: 'tariffs.table.col13', section: 'Тарифы', label: 'Колонка — от 13 дней', type: 'text', sort: 207, value: 'от 13 дней' },
  { key: 'tariffs.table.col30', section: 'Тарифы', label: 'Колонка — от 30 дней', type: 'text', sort: 208, value: 'от 30 дней' },
  { key: 'tariffs.table.colDeposit', section: 'Тарифы', label: 'Колонка — Залог', type: 'text', sort: 209, value: 'Залог' },
  { key: 'tariffs.table.colMileage', section: 'Тарифы', label: 'Колонка — Пробег/сут', type: 'text', sort: 210, value: 'Пробег/сут' },
  { key: 'tariffs.table.colOvermileage', section: 'Тарифы', label: 'Колонка — Перекат/км', type: 'text', sort: 211, value: 'Перекат/км' },
  { key: 'tariffs.table.colPhoto', section: 'Тарифы', label: 'Колонка — Фотосессия/час', type: 'text', sort: 212, value: 'Фотосессия/час' },
  { key: 'tariffs.table.priceNegotiable', section: 'Тарифы', label: 'Цена — договорная', type: 'text', sort: 213, value: 'договорная' },
  { key: 'tariffs.notes.photo.link', section: 'Тарифы', label: 'Ссылка «Подробнее об аренде для фото»', type: 'text', sort: 214, value: 'Подробнее об аренде для фото →' },
  // ── Долгосрочная ──
  { key: 'longterm.head.title', section: 'Долгосрочная', label: 'Заголовок страницы', type: 'html', sort: 10, value: 'Премиальное авто <em>в долгосрочную аренду</em>' },
  { key: 'longterm.head.lead', section: 'Долгосрочная', label: 'Подзаголовок', type: 'textarea', sort: 20, value: 'Подписка AURIX MOTORS от 1 месяца с фиксированным ежемесячным платежом. Свежий автомобиль премиум-класса, полное обслуживание, страховка, сезонная резина и подменное авто — всё включено в один платёж. Меняйте модель, когда захотите, без забот о покупке и содержании.' },
  { key: 'longterm.head.cta1', section: 'Долгосрочная', label: 'Кнопка CTA 1', type: 'text', sort: 30, value: 'Подобрать автомобиль' },
  { key: 'longterm.head.cta2', section: 'Долгосрочная', label: 'Кнопка CTA 2', type: 'text', sort: 40, value: 'Получить расчёт' },
  { key: 'longterm.benefits.eyebrow', section: 'Долгосрочная', label: 'Надзаголовок «Преимущества»', type: 'text', sort: 50, value: 'Преимущества' },
  { key: 'longterm.benefits.title', section: 'Долгосрочная', label: 'Заголовок «Преимущества»', type: 'html', sort: 60, value: 'Почему <em>долгосрочная</em> аренда' },
  { key: 'longterm.head.crumbHome', section: 'Долгосрочная', label: 'Хлебные крошки — Главная', type: 'text', sort: 200, value: 'Главная' },
  { key: 'longterm.head.crumbCurrent', section: 'Долгосрочная', label: 'Хлебные крошки — текущая страница', type: 'text', sort: 201, value: 'Долгосрочная аренда' },
  { key: 'longterm.benefits.item0title', section: 'Долгосрочная', label: 'Преимущество 1 — заголовок', type: 'text', sort: 202, value: 'Фиксированная цена' },
  { key: 'longterm.benefits.item0text', section: 'Долгосрочная', label: 'Преимущество 1 — описание', type: 'textarea', sort: 203, value: 'Один платёж в месяц — никаких сюрпризов. Ставка фиксируется на весь срок договора.' },
  { key: 'longterm.benefits.item1title', section: 'Долгосрочная', label: 'Преимущество 2 — заголовок', type: 'text', sort: 204, value: 'Сервис включён' },
  { key: 'longterm.benefits.item1text', section: 'Долгосрочная', label: 'Преимущество 2 — описание', type: 'textarea', sort: 205, value: 'ТО, замена жидкостей, шиномонтаж и сезонная резина — всё за наш счёт.' },
  { key: 'longterm.benefits.item2title', section: 'Долгосрочная', label: 'Преимущество 3 — заголовок', type: 'text', sort: 206, value: 'Полная страховка' },
  { key: 'longterm.benefits.item2text', section: 'Долгосрочная', label: 'Преимущество 3 — описание', type: 'textarea', sort: 207, value: 'КАСКО + ОСАГО + страхование жизни. Без франшизы при стандартных рисках.' },
  { key: 'longterm.benefits.item3title', section: 'Долгосрочная', label: 'Преимущество 4 — заголовок', type: 'text', sort: 208, value: 'Замена авто' },
  { key: 'longterm.benefits.item3text', section: 'Долгосрочная', label: 'Преимущество 4 — описание', type: 'textarea', sort: 209, value: 'Каждые 6 месяцев можно сменить модель. Подменный автомобиль на время сервиса.' },
  { key: 'longterm.benefits.item4title', section: 'Долгосрочная', label: 'Преимущество 5 — заголовок', type: 'text', sort: 210, value: 'Залог обязателен' },
  { key: 'longterm.benefits.item4text', section: 'Долгосрочная', label: 'Преимущество 5 — описание', type: 'textarea', sort: 211, value: 'Залог оформляется всегда и возвращается после сдачи автомобиля — гарантия сохранности премиального авто.' },
  { key: 'longterm.benefits.item5title', section: 'Долгосрочная', label: 'Преимущество 6 — заголовок', type: 'text', sort: 212, value: 'Подача и возврат' },
  { key: 'longterm.benefits.item5text', section: 'Долгосрочная', label: 'Преимущество 6 — описание', type: 'textarea', sort: 213, value: 'Машину привезут и заберут в удобное место. Бесплатно в пределах Москвы.' },
  { key: 'longterm.tariffs.eyebrow', section: 'Долгосрочная', label: 'Тарифы — эйбрау', type: 'text', sort: 214, value: 'Тарифы' },
  { key: 'longterm.tariffs.title', section: 'Долгосрочная', label: 'Тарифы — заголовок', type: 'html', sort: 215, value: 'Стоимость <em>аренды</em>' },
  { key: 'longterm.tariffs.p1title', section: 'Долгосрочная', label: 'Тариф 1 мес — название', type: 'text', sort: 216, value: '1 месяц' },
  { key: 'longterm.tariffs.p1price', section: 'Долгосрочная', label: 'Тариф 1 мес — цена', type: 'text', sort: 217, value: 'от 720 000 ₽' },
  { key: 'longterm.tariffs.p1per', section: 'Долгосрочная', label: 'Тариф 1 мес — период', type: 'text', sort: 218, value: 'в месяц' },
  { key: 'longterm.tariffs.p1f0', section: 'Долгосрочная', label: 'Тариф 1 мес — пункт 1', type: 'text', sort: 219, value: 'Любой автомобиль из автопарка' },
  { key: 'longterm.tariffs.p1f1', section: 'Долгосрочная', label: 'Тариф 1 мес — пункт 2', type: 'text', sort: 220, value: '3 000 км в месяц включено' },
  { key: 'longterm.tariffs.p1f2', section: 'Долгосрочная', label: 'Тариф 1 мес — пункт 3', type: 'text', sort: 221, value: 'Полная страховка' },
  { key: 'longterm.tariffs.p1f3', section: 'Долгосрочная', label: 'Тариф 1 мес — пункт 4', type: 'text', sort: 222, value: 'Подача и возврат бесплатно' },
  { key: 'longterm.tariffs.p3title', section: 'Долгосрочная', label: 'Тариф 3 мес — название', type: 'text', sort: 223, value: '3 месяца' },
  { key: 'longterm.tariffs.p3price', section: 'Долгосрочная', label: 'Тариф 3 мес — цена', type: 'text', sort: 224, value: 'от 620 000 ₽' },
  { key: 'longterm.tariffs.p3per', section: 'Долгосрочная', label: 'Тариф 3 мес — период', type: 'text', sort: 225, value: 'в месяц · экономия 15%' },
  { key: 'longterm.tariffs.p3f0', section: 'Долгосрочная', label: 'Тариф 3 мес — пункт 1', type: 'text', sort: 226, value: 'Любой автомобиль из автопарка' },
  { key: 'longterm.tariffs.p3f1', section: 'Долгосрочная', label: 'Тариф 3 мес — пункт 2', type: 'text', sort: 227, value: '4 000 км в месяц включено' },
  { key: 'longterm.tariffs.p3f2', section: 'Долгосрочная', label: 'Тариф 3 мес — пункт 3', type: 'text', sort: 228, value: 'Полная страховка + GAP' },
  { key: 'longterm.tariffs.p3f3', section: 'Долгосрочная', label: 'Тариф 3 мес — пункт 4', type: 'text', sort: 229, value: 'Сервис включён' },
  { key: 'longterm.tariffs.p3f4', section: 'Долгосрочная', label: 'Тариф 3 мес — пункт 5', type: 'text', sort: 230, value: 'Замена авто 1 раз' },
  { key: 'longterm.tariffs.p6title', section: 'Долгосрочная', label: 'Тариф 6+ мес — название', type: 'text', sort: 231, value: '6+ месяцев' },
  { key: 'longterm.tariffs.p6price', section: 'Долгосрочная', label: 'Тариф 6+ мес — цена', type: 'text', sort: 232, value: 'от 540 000 ₽' },
  { key: 'longterm.tariffs.p6per', section: 'Долгосрочная', label: 'Тариф 6+ мес — период', type: 'text', sort: 233, value: 'в месяц · экономия 25%' },
  { key: 'longterm.tariffs.p6f0', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 1', type: 'text', sort: 234, value: 'Премиум подбор' },
  { key: 'longterm.tariffs.p6f1', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 2', type: 'text', sort: 235, value: '5 000 км в месяц включено' },
  { key: 'longterm.tariffs.p6f2', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 3', type: 'text', sort: 236, value: 'Полная страховка + GAP' },
  { key: 'longterm.tariffs.p6f3', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 4', type: 'text', sort: 237, value: 'Сервис, шины, мойка' },
  { key: 'longterm.tariffs.p6f4', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 5', type: 'text', sort: 238, value: 'Подменное авто 24/7' },
  { key: 'longterm.tariffs.p6f5', section: 'Долгосрочная', label: 'Тариф 6+ мес — пункт 6', type: 'text', sort: 239, value: 'Клубная карта в подарок' },
  { key: 'longterm.tariffs.cta', section: 'Долгосрочная', label: 'Тарифы — кнопка «Выбрать авто»', type: 'text', sort: 240, value: 'Выбрать авто' },
  // ── Аренда для фото ──
  { key: 'photo.hero.title', section: 'Аренда для фото', label: 'Заголовок страницы', type: 'html', sort: 10, value: 'Аренда авто <em>для фотосессий</em>' },
  { key: 'photo.hero.lead', section: 'Аренда для фото', label: 'Подзаголовок', type: 'textarea', sort: 20, value: 'Премиальный автомобиль на час-полтора для фотосессии, съёмки клипа, свадьбы или праздника. Без пробега и лишней бумажной волокиты — машина подаётся к месту съёмки, вы получаете кадры, мы забираем авто. Тариф указан за час.' },
  { key: 'photo.hero.ctaBook', section: 'Аренда для фото', label: 'Кнопка «Забронировать»', type: 'text', sort: 30, value: 'Забронировать съёмку' },
  { key: 'photo.hero.ctaCatalog', section: 'Аренда для фото', label: 'Кнопка «Автопарк»', type: 'text', sort: 40, value: 'Смотреть автопарк' },
  { key: 'photo.how.eyebrow', section: 'Аренда для фото', label: 'Надзаголовок «Как это работает»', type: 'text', sort: 50, value: 'Как это работает' },
  { key: 'photo.how.title', section: 'Аренда для фото', label: 'Заголовок «Как это работает»', type: 'html', sort: 60, value: 'Просто и <em>быстро</em>' },
  { key: 'photo.how.step1Title', section: 'Аренда для фото', label: 'Шаг 1 — заголовок', type: 'text', sort: 70, value: '1. Выберите авто и время' },
  { key: 'photo.how.step1Text', section: 'Аренда для фото', label: 'Шаг 1 — текст', type: 'textarea', sort: 80, value: 'Любой автомобиль из списка ниже. Минимальная аренда — 1 час. Возможна съёмка день в день — уточните у менеджера.' },
  { key: 'photo.how.step2Title', section: 'Аренда для фото', label: 'Шаг 2 — заголовок', type: 'text', sort: 90, value: '2. Подача к месту съёмки' },
  { key: 'photo.how.step2Text', section: 'Аренда для фото', label: 'Шаг 2 — текст', type: 'textarea', sort: 100, value: 'Привезём автомобиль в любую точку Москвы и МО — студия, парк, набережная, площадка мероприятия.' },
  { key: 'photo.how.step3Title', section: 'Аренда для фото', label: 'Шаг 3 — заголовок', type: 'text', sort: 110, value: '3. Снимайте' },
  { key: 'photo.how.step3Text', section: 'Аренда для фото', label: 'Шаг 3 — текст', type: 'textarea', sort: 120, value: 'Машина в вашем распоряжении на время съёмки. Фотограф, свет, декор — на ваше усмотрение. Поездки — по договорённости.' },
  { key: 'photo.crumb.home', section: 'Аренда для фото', label: 'Хлебные крошки — Главная', type: 'text', sort: 200, value: 'Главная' },
  { key: 'photo.crumb.current', section: 'Аренда для фото', label: 'Хлебные крошки — текущая', type: 'text', sort: 201, value: 'Аренда для фото' },
  { key: 'photo.rates.eyebrow', section: 'Аренда для фото', label: 'Тарифы — эйбрау', type: 'text', sort: 202, value: 'Тарифы' },
  { key: 'photo.rates.title', section: 'Аренда для фото', label: 'Тарифы — заголовок', type: 'html', sort: 203, value: 'Стоимость <em>за час</em>' },
  { key: 'photo.rates.loading', section: 'Аренда для фото', label: 'Тарифы — загрузка', type: 'text', sort: 204, value: 'Загрузка…' },
  { key: 'photo.rates.emptyPre', section: 'Аренда для фото', label: 'Тарифы пусто — до ссылки', type: 'text', sort: 205, value: 'Тарифы уточняйте у менеджера — ' },
  { key: 'photo.rates.emptyLink', section: 'Аренда для фото', label: 'Тарифы пусто — ссылка', type: 'text', sort: 206, value: 'свяжитесь с нами' },
  { key: 'photo.rates.emptyPost', section: 'Аренда для фото', label: 'Тарифы пусто — после ссылки', type: 'text', sort: 207, value: '.' },
  { key: 'photo.card.priceLabel', section: 'Аренда для фото', label: 'Карточка авто — подпись цены', type: 'text', sort: 208, value: 'фотосессия · час' },
  { key: 'photo.terms.title', section: 'Аренда для фото', label: 'Условия — заголовок', type: 'text', sort: 209, value: 'Условия' },
  { key: 'photo.terms.item1', section: 'Аренда для фото', label: 'Условия — пункт 1', type: 'textarea', sort: 210, value: 'Тариф действует для статичной съёмки без пробега; поездки в кадре — по договорённости.' },
  { key: 'photo.terms.item2', section: 'Аренда для фото', label: 'Условия — пункт 2', type: 'textarea', sort: 211, value: 'Подача и возврат по Москве оплачиваются отдельно в зависимости от адреса.' },
  { key: 'photo.terms.item3', section: 'Аренда для фото', label: 'Условия — пункт 3', type: 'textarea', sort: 212, value: 'Залог обязателен и возвращается сразу после завершения съёмки.' },
  { key: 'photo.terms.item4Pre', section: 'Аренда для фото', label: 'Условия пункт 4 — до ссылки', type: 'text', sort: 213, value: 'Бронь подтверждает менеджер — ' },
  { key: 'photo.terms.item4Link', section: 'Аренда для фото', label: 'Условия пункт 4 — ссылка', type: 'text', sort: 214, value: 'напишите нам' },
  { key: 'photo.terms.item4Post', section: 'Аренда для фото', label: 'Условия пункт 4 — после ссылки', type: 'text', sort: 215, value: ' или оставьте заявку на странице авто.' },
  { key: 'photo.cta.book', section: 'Аренда для фото', label: 'Нижняя кнопка — забронировать', type: 'text', sort: 216, value: 'Забронировать съёмку' },
  // ── Контакты ──
  { key: 'contacts.hero.title', section: 'Контакты', label: 'Заголовок страницы', type: 'html', sort: 10, value: 'Свяжитесь <em>с нами</em>' },
  { key: 'contacts.hero.lead', section: 'Контакты', label: 'Подзаголовок', type: 'textarea', sort: 20, value: 'Мы на связи 24/7. Звоните, пишите в мессенджеры или приезжайте в наш шоурум.' },
  { key: 'contacts.info.phoneLabel', section: 'Контакты', label: 'Подпись блока «Телефон»', type: 'text', sort: 30, value: 'Телефон · 24/7' },
  { key: 'contacts.info.phone', section: 'Контакты', label: 'Телефон', type: 'text', sort: 40, value: '+7 925 312 28 02' },
  { key: 'contacts.info.phoneNote', section: 'Контакты', label: 'Примечание к телефону', type: 'text', sort: 50, value: 'Москва, основной номер' },
  { key: 'contacts.info.messengersLabel', section: 'Контакты', label: 'Подпись «Мессенджеры»', type: 'text', sort: 60, value: 'Мессенджеры' },
  { key: 'contacts.info.messengers', section: 'Контакты', label: 'Мессенджеры (ник)', type: 'text', sort: 70, value: '@aurixmotors' },
  { key: 'contacts.info.messengersNote', section: 'Контакты', label: 'Примечание к мессенджерам', type: 'text', sort: 80, value: 'Telegram · WhatsApp · iMessage' },
  { key: 'contacts.info.emailLabel', section: 'Контакты', label: 'Подпись блока «Email»', type: 'text', sort: 90, value: 'Email' },
  { key: 'contacts.info.email', section: 'Контакты', label: 'Email', type: 'text', sort: 100, value: 'info@aurixmotors.com' },
  { key: 'contacts.info.emailNote', section: 'Контакты', label: 'Примечание к email', type: 'text', sort: 110, value: 'booking@aurixmotors.com — бронирование' },
  { key: 'contacts.info.addressLabel', section: 'Контакты', label: 'Подпись блока «Шоурум»', type: 'text', sort: 120, value: 'Шоурум' },
  { key: 'contacts.info.address', section: 'Контакты', label: 'Адрес', type: 'text', sort: 130, value: 'Москва, Олимпийский проспект, 12' },
  { key: 'contacts.info.hours', section: 'Контакты', label: 'Часы работы', type: 'text', sort: 140, value: 'Ежедневно, 10:00–20:00' },
  { key: 'contacts.form.title', section: 'Контакты', label: 'Заголовок формы', type: 'text', sort: 150, value: 'Оставьте заявку' },
  { key: 'contacts.form.note', section: 'Контакты', label: 'Примечание под формой', type: 'text', sort: 160, value: 'Перезвоним в течение 5 минут' },
  { key: 'contacts.form.submit', section: 'Контакты', label: 'Кнопка отправки формы', type: 'text', sort: 170, value: 'Отправить' },
  { key: 'contacts.hero.crumbHome', section: 'Контакты', label: 'Хлебные крошки — Главная', type: 'text', sort: 200, value: 'Главная' },
  { key: 'contacts.hero.crumbCurrent', section: 'Контакты', label: 'Хлебные крошки — текущая', type: 'text', sort: 201, value: 'Контакты' },
  { key: 'contacts.form.success', section: 'Контакты', label: 'Успех отправки формы', type: 'textarea', sort: 204, value: 'Заявка успешно отправлена! Мы перезвоним вам в течение 5 минут.' },
  { key: 'contacts.form.labelName', section: 'Контакты', label: 'Лейбл поля — Имя', type: 'text', sort: 205, value: 'Имя' },
  { key: 'contacts.form.labelPhone', section: 'Контакты', label: 'Лейбл поля — Телефон', type: 'text', sort: 206, value: 'Телефон' },
  { key: 'contacts.form.labelCar', section: 'Контакты', label: 'Лейбл поля — Автомобиль', type: 'text', sort: 207, value: 'Какой автомобиль вас интересует' },
  { key: 'contacts.form.labelMessage', section: 'Контакты', label: 'Лейбл поля — Сообщение', type: 'text', sort: 208, value: 'Сообщение' },
  { key: 'contacts.form.loading', section: 'Контакты', label: 'Кнопка — состояние отправки', type: 'text', sort: 209, value: 'Отправка...' },
  // ── Клуб ──
  { key: 'club.breadcrumbs.home', section: 'Клуб', label: 'Хлебные крошки: Главная', type: 'text', sort: 10, value: 'Главная' },
  { key: 'club.breadcrumbs.current', section: 'Клуб', label: 'Хлебные крошки: текущая', type: 'text', sort: 20, value: 'Клубная карта' },
  { key: 'club.hero.title', section: 'Клуб', label: 'Заголовок страницы (H1)', type: 'html', sort: 30, value: 'Клубная карта <em>AURIX MOTORS</em>' },
  { key: 'club.card.member', section: 'Клуб', label: 'Карта: подпись Member', type: 'text', sort: 40, value: 'Member' },
  { key: 'club.card.validthru', section: 'Клуб', label: 'Карта: подпись Valid Thru', type: 'text', sort: 50, value: 'Valid Thru' },
  { key: 'club.privileges.eyebrow', section: 'Клуб', label: 'Привилегии: эйбрау', type: 'text', sort: 60, value: 'Привилегии' },
  { key: 'club.privileges.title', section: 'Клуб', label: 'Привилегии: заголовок', type: 'html', sort: 70, value: 'Закрытый клуб <em class="gold">AURIX MOTORS</em>' },
  { key: 'club.privileges.lead', section: 'Клуб', label: 'Привилегии: лид-абзац', type: 'textarea', sort: 80, value: 'Клубная карта — это не просто скидка, а статус. Разместите депозит и получите персональную скидку от 5 до 40% на любую аренду. Карта действует без ограничений по числу поездок.' },
  { key: 'club.perks.item0title', section: 'Клуб', label: 'Перк 1: заголовок', type: 'text', sort: 90, value: 'Скидка до −40%' },
  { key: 'club.perks.item0desc', section: 'Клуб', label: 'Перк 1: описание', type: 'text', sort: 100, value: 'На любую аренду в любой день. Скидка применяется автоматически.' },
  { key: 'club.perks.item1title', section: 'Клуб', label: 'Перк 2: заголовок', type: 'text', sort: 110, value: 'Приоритет подачи' },
  { key: 'club.perks.item1desc', section: 'Клуб', label: 'Перк 2: описание', type: 'text', sort: 120, value: 'Держатели карт получают приоритет при бронировании дефицитных моделей.' },
  { key: 'club.perks.item2title', section: 'Клуб', label: 'Перк 3: заголовок', type: 'text', sort: 130, value: 'Без срока' },
  { key: 'club.perks.item2desc', section: 'Клуб', label: 'Перк 3: описание', type: 'text', sort: 140, value: 'Карты уровня Премиум и Black действуют бессрочно — без ежегодного продления.' },
  { key: 'club.perks.item3title', section: 'Клуб', label: 'Перк 4: заголовок', type: 'text', sort: 150, value: 'Закрытые ивенты' },
  { key: 'club.perks.item3desc', section: 'Клуб', label: 'Перк 4: описание', type: 'text', sort: 160, value: 'Тест-драйвы новинок, закрытые ужины и партнёрские мероприятия.' },
  { key: 'club.levels.eyebrow', section: 'Клуб', label: 'Уровни: эйбрау', type: 'text', sort: 170, value: 'Уровни членства' },
  { key: 'club.levels.title', section: 'Клуб', label: 'Уровни: заголовок', type: 'html', sort: 180, value: 'Выберите свой <em>статус</em>' },
  { key: 'club.levels.spentlabel', section: 'Клуб', label: 'Уровни: подпись суммы аренд', type: 'text', sort: 190, value: 'Сумма завершенных аренд:' },
  { key: 'club.levels.yourlevel', section: 'Клуб', label: 'Уровни: подпись вашего уровня', type: 'text', sort: 200, value: 'Ваш уровень:' },
  { key: 'club.levels.statusbadge', section: 'Клуб', label: 'Уровни: бейдж «Ваш статус»', type: 'text', sort: 210, value: 'Ваш статус' },
  { key: 'club.levels.discountlabel', section: 'Клуб', label: 'Уровни: подпись «скидка на аренду»', type: 'text', sort: 220, value: 'скидка на аренду' },
  { key: 'club.levels.depositlabel', section: 'Клуб', label: 'Уровни: подпись «депозит»', type: 'text', sort: 230, value: 'депозит' },
  { key: 'club.levels.ctaactive', section: 'Клуб', label: 'Уровни: CTA (активный статус)', type: 'text', sort: 240, value: 'Условия обслуживания' },
  { key: 'club.levels.cta', section: 'Клуб', label: 'Уровни: CTA (получить карту)', type: 'text', sort: 250, value: 'Получить карту' },
  { key: 'club.tier0.perk0', section: 'Клуб', label: 'Старт: перк 1', type: 'text', sort: 260, value: 'Скидка 5% на все аренды' },
  { key: 'club.tier0.perk1', section: 'Клуб', label: 'Старт: перк 2', type: 'text', sort: 270, value: 'Приоритетная поддержка' },
  { key: 'club.tier0.perk2', section: 'Клуб', label: 'Старт: перк 3', type: 'text', sort: 280, value: 'Бронирование первым' },
  { key: 'club.tier0.perk3', section: 'Клуб', label: 'Старт: перк 4', type: 'text', sort: 290, value: 'Срок действия 1 год' },
  { key: 'club.tier1.perk0', section: 'Клуб', label: 'Комфорт: перк 1', type: 'text', sort: 300, value: 'Скидка 15% на все аренды' },
  { key: 'club.tier1.perk1', section: 'Клуб', label: 'Комфорт: перк 2', type: 'text', sort: 310, value: 'Приоритет на дефицитные модели' },
  { key: 'club.tier1.perk2', section: 'Клуб', label: 'Комфорт: перк 3', type: 'text', sort: 320, value: 'Приоритетная поддержка 24/7' },
  { key: 'club.tier1.perk3', section: 'Клуб', label: 'Комфорт: перк 4', type: 'text', sort: 330, value: 'Срок действия 1 год' },
  { key: 'club.tier2.perk0', section: 'Клуб', label: 'Премиум: перк 1', type: 'text', sort: 340, value: 'Скидка 25% на все аренды' },
  { key: 'club.tier2.perk1', section: 'Клуб', label: 'Премиум: перк 2', type: 'text', sort: 350, value: 'Бессрочная карта' },
  { key: 'club.tier2.perk2', section: 'Клуб', label: 'Премиум: перк 3', type: 'text', sort: 360, value: 'VIP-сопровождение и доступ к закрытым ивентам' },
  { key: 'club.tier2.perk3', section: 'Клуб', label: 'Премиум: перк 4', type: 'text', sort: 370, value: 'Личный менеджер' },
  { key: 'club.tier3.perk0', section: 'Клуб', label: 'Black: перк 1', type: 'text', sort: 380, value: 'Скидка 40% — максимальная privilege' },
  { key: 'club.tier3.perk1', section: 'Клуб', label: 'Black: перк 2', type: 'text', sort: 390, value: 'Бессрочная карта' },
  { key: 'club.tier3.perk2', section: 'Клуб', label: 'Black: перк 3', type: 'text', sort: 400, value: 'Личный менеджер 24/7' },
  { key: 'club.tier3.perk3', section: 'Клуб', label: 'Black: перк 4', type: 'text', sort: 410, value: 'Все закрытые ивенты и партнёрские мероприятия' },
  { key: 'club.tier3.perk4', section: 'Клуб', label: 'Black: перк 5', type: 'text', sort: 420, value: 'Concierge сервис' },
  { key: 'club.gift.eyebrow', section: 'Клуб', label: 'Сертификаты: эйбрау', type: 'text', sort: 430, value: 'Подарочные сертификаты' },
  { key: 'club.gift.title', section: 'Клуб', label: 'Сертификаты: заголовок', type: 'html', sort: 440, value: 'Подарите <em>впечатления</em>' },
  { key: 'club.gift.desc', section: 'Клуб', label: 'Сертификаты: описание', type: 'html', sort: 450, value: 'Подарочный сертификат на аренду любого автомобиля из нашего парка. Стоимость сертификата равна стоимости <strong>одних суток аренды</strong> выбранного автомобиля. Срок действия сертификата — <strong>1 год</strong> с даты оформления.' },
  { key: 'club.gift.cta', section: 'Клуб', label: 'Сертификаты: кнопка', type: 'text', sort: 460, value: 'Оформить сертификат' },
  // ── Сдать авто ──
  { key: 'rentout.crumb.home', section: 'Сдать авто', label: 'Хлебные крошки: Главная', type: 'text', sort: 10, value: 'Главная' },
  { key: 'rentout.crumb.current', section: 'Сдать авто', label: 'Хлебные крошки: текущая', type: 'text', sort: 20, value: 'Сдать свою машину' },
  { key: 'rentout.hero.title', section: 'Сдать авто', label: 'Заголовок страницы (H1)', type: 'html', sort: 30, value: 'Сдайте свой автомобиль в <em>управление</em>' },
  { key: 'rentout.hero.lead', section: 'Сдать авто', label: 'Подзаголовок / лид', type: 'textarea', sort: 40, value: 'Передайте премиальный автомобиль команде AURIX MOTORS — мы возьмём на себя бронирования, обслуживание, страховку и сервис. Вы получаете стабильный доход и прозрачную отчётность.' },
  { key: 'rentout.step1.title', section: 'Сдать авто', label: 'Шаг 01: заголовок', type: 'text', sort: 50, value: 'Заявка' },
  { key: 'rentout.step1.desc', section: 'Сдать авто', label: 'Шаг 01: описание', type: 'textarea', sort: 60, value: 'Отправляете данные авто и фото. Менеджер связывается в течение часа.' },
  { key: 'rentout.step2.title', section: 'Сдать авто', label: 'Шаг 02: заголовок', type: 'text', sort: 70, value: 'Оценка' },
  { key: 'rentout.step2.desc', section: 'Сдать авто', label: 'Шаг 02: описание', type: 'textarea', sort: 80, value: 'Технический осмотр, оценка стоимости аренды и подготовка авто к работе.' },
  { key: 'rentout.step3.title', section: 'Сдать авто', label: 'Шаг 03: заголовок', type: 'text', sort: 90, value: 'Договор' },
  { key: 'rentout.step3.desc', section: 'Сдать авто', label: 'Шаг 03: описание', type: 'textarea', sort: 100, value: 'Прозрачные условия, страхование от рисков, фиксированная доля.' },
  { key: 'rentout.step4.title', section: 'Сдать авто', label: 'Шаг 04: заголовок', type: 'text', sort: 110, value: 'Доход' },
  { key: 'rentout.step4.desc', section: 'Сдать авто', label: 'Шаг 04: описание', type: 'textarea', sort: 120, value: 'До 70% от аренды. Выплаты дважды в месяц, личный кабинет с отчётами.' },
  { key: 'rentout.form.eyebrow', section: 'Сдать авто', label: 'Эйбрау формы', type: 'text', sort: 130, value: 'Заявка' },
  { key: 'rentout.form.title', section: 'Сдать авто', label: 'Заголовок формы (H2)', type: 'html', sort: 140, value: 'Расскажите о <em>вашем авто</em>' },
  { key: 'rentout.auth.prompt', section: 'Сдать авто', label: 'Требуется вход: текст', type: 'text', sort: 150, value: 'Чтобы оставить заявку, необходимо войти в систему.' },
  { key: 'rentout.auth.login', section: 'Сдать авто', label: 'Кнопка: Войти', type: 'text', sort: 160, value: 'Войти' },
  { key: 'rentout.success.title', section: 'Сдать авто', label: 'Успех: заголовок', type: 'text', sort: 170, value: 'Заявка успешно отправлена!' },
  { key: 'rentout.success.desc', section: 'Сдать авто', label: 'Успех: описание', type: 'textarea', sort: 180, value: 'Ваш автомобиль отправлен на модерацию. Мы свяжемся с вами в ближайшее время.' },
  { key: 'rentout.success.cabinet', section: 'Сдать авто', label: 'Кнопка: В личный кабинет', type: 'text', sort: 190, value: 'В личный кабинет' },
  { key: 'rentout.field.brand', section: 'Сдать авто', label: 'Поле: Марка', type: 'text', sort: 200, value: 'Марка *' },
  { key: 'rentout.field.model', section: 'Сдать авто', label: 'Поле: Модель', type: 'text', sort: 210, value: 'Модель *' },
  { key: 'rentout.field.year', section: 'Сдать авто', label: 'Поле: Год выпуска', type: 'text', sort: 220, value: 'Год выпуска *' },
  { key: 'rentout.field.body', section: 'Сдать авто', label: 'Поле: Кузов', type: 'text', sort: 230, value: 'Кузов' },
  { key: 'rentout.field.engine', section: 'Сдать авто', label: 'Поле: Двигатель', type: 'text', sort: 240, value: 'Двигатель' },
  { key: 'rentout.field.power', section: 'Сдать авто', label: 'Поле: Мощность (л.с.)', type: 'text', sort: 250, value: 'Мощность (л.с.)' },
  { key: 'rentout.field.price', section: 'Сдать авто', label: 'Поле: Желаемая цена (в сутки)', type: 'text', sort: 260, value: 'Желаемая цена (в сутки) *' },
  { key: 'rentout.field.image', section: 'Сдать авто', label: 'Поле: URL фотографии', type: 'text', sort: 270, value: 'URL фотографии (временное решение) *' },
  { key: 'rentout.field.desc', section: 'Сдать авто', label: 'Поле: Комментарий / Описание', type: 'text', sort: 280, value: 'Комментарий / Описание' },
  { key: 'rentout.form.note', section: 'Сдать авто', label: 'Примечание под формой', type: 'textarea', sort: 290, value: 'Нажимая «Отправить», вы принимаете условия партнерской программы AURIX MOTORS.' },
  { key: 'rentout.form.submit', section: 'Сдать авто', label: 'Кнопка: Отправить заявку', type: 'text', sort: 300, value: 'Отправить заявку' },
  { key: 'rentout.form.submitting', section: 'Сдать авто', label: 'Кнопка: состояние отправки', type: 'text', sort: 310, value: 'Отправка...' },
];
